//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_WCF.ServiceReference1 {
    
    

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : WcfServiceLibrary1.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<WcfServiceLibrary1.IEmployeeService>, WcfServiceLibrary1.IEmployeeService
    {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WcfServiceLibrary1.Employee> getEmployees() {
            return base.Channel.getEmployees();
        }
        
        public WcfServiceLibrary1.Employee getEmployee(int ID) {
            return base.Channel.getEmployee(ID);
        }
        
        public bool editEmployeeByID(int id, WcfServiceLibrary1.Employee newVal) {
            return base.Channel.editEmployeeByID(id, newVal);
        }
        
        public bool insertEmployee(WcfServiceLibrary1.Employee newEmp) {
            return base.Channel.insertEmployee(newEmp);
        }
        
        public bool deleteEmployee(int ID) {
            return base.Channel.deleteEmployee(ID);
        }
    }
}
